### ISSUE TITLE
Can you publish it to Hex?

### ISSUE THREAD

**Issue by MonsieurV** [odo/nested#4]
Hi @odo!

I use your lib for a project ([YtoTech/geo_sensors_gateway](https://github.com/YtoTech/geo_sensors_gateway)).

As on [Hex](https://hex.pm) you can't publish a package if all dependencies are their-self published, it would come handy to have this project published. :)

**Comment by odo** [comment]
Here you go: https://hex.pm/packages/nested

**Comment by MonsieurV** [comment]
Thanks @odo!
